apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-tdc-future-2023
  namespace: tdc

spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-tdc-future-2023
  template:
    metadata:
      labels:
        app: app-tdc-future-2023
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: type
                operator: In
                values:
                - app-tdc-future-2023
      containers:
        - name: app-tdc-future-2023
          image: container-image
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
            limits:
              cpu: 256m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 2
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 15
            successThreshold: 1
          ports:
          - containerPort: 3000