apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: app-tdc-future-2023-hpa
  namespace: tdc

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: app-tdc-future-2023
    kind: Deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40