name: CI tdc-future-devops

on:
  push:
    branches:
      - main
env:
  CONTAINER_REPOSITORY: danielrodriguess/app-tdc-future-2023
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7 )
          echo "::set-output name=sha::$SHA"
      
      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build docker image
        run: docker build -t $CONTAINER_REPOSITORY:${{ steps.generate_sha.outputs.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push $CONTAINER_REPOSITORY:${{ steps.generate_sha.outputs.sha }}
          docker tag $CONTAINER_REPOSITORY:${{ steps.generate_sha.outputs.sha }} $CONTAINER_REPOSITORY:latest
          docker push $CONTAINER_REPOSITORY:latest
