name: CI tdc-future-devops

on:
  push:
    branches:
      - main
env:
  CONTAINER_REPOSITORY: danielrodriguess/app-tdc-future-2023
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate sha
        id: generate-sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7 )
          echo "SHA=$SHA" >> $GITHUB_OUTPUT
      
      - name: Install packages
        run: yarn install --immutable

      - name: Build docker image
        env:
          SHA: ${{ steps.generate-sha.outputs.SHA }}
        run: docker build -t $CONTAINER_REPOSITORY:$SHA .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        env:
          SHA: ${{ steps.generate-sha.outputs.SHA }}
        run: |
          docker push $CONTAINER_REPOSITORY:$SHA
          docker tag $CONTAINER_REPOSITORY:$SHA $CONTAINER_REPOSITORY:latest
          docker push $CONTAINER_REPOSITORY:latest
      
      - name: "Update Deployment image tag"
        env:
          SHA: ${{ steps.generate-sha.outputs.SHA }}
        working-directory: "k8s/kustomize"
        run: |
          kustomize edit set image app-image=$CONTAINER_REPOSITORY:$SHA
      
      - name: Commit files
        env:
          SHA: ${{ steps.generate-sha.outputs.SHA }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "feat: Update deployment image tag to $SHA - [skip ci]"

      - name: "Push updated image tag"
        uses: ad-m/github-push-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}